"""添加请求参数记录字段

Revision ID: 3b55dccdc0a7
Revises: f5fcb9d73be2
Create Date: 2025-08-02 11:59:54.179932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b55dccdc0a7'
down_revision: Union[str, Sequence[str], None] = 'f5fcb9d73be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('request_params', sa.JSON(), nullable=True, comment='请求参数（已脱敏）'))
    op.add_column('access_logs', sa.Column('request_body', sa.JSON(), nullable=True, comment='请求体（已脱敏）'))
    op.add_column('access_logs', sa.Column('response_data', sa.JSON(), nullable=True, comment='响应数据（已脱敏）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'response_data')
    op.drop_column('access_logs', 'request_body')
    op.drop_column('access_logs', 'request_params')
    # ### end Alembic commands ###
