"""Add site_config table

Revision ID: c69e76efcd0a
Revises: 834cc849d4eb
Create Date: 2025-08-02 23:33:46.835834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69e76efcd0a'
down_revision: Union[str, Sequence[str], None] = '834cc849d4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('category', sa.Enum('BASIC', 'CONTACT', 'SOCIAL', 'SEO', 'OTHER', name='configcategory'), nullable=False, comment='配置分类'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.Column('data_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'URL', 'EMAIL', name='configdatatype'), nullable=True, comment='数据类型'),
    sa.Column('is_public', sa.String(length=10), nullable=True, comment='是否公开显示'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_configs_id'), 'site_configs', ['id'], unique=False)
    op.create_index(op.f('ix_site_configs_key'), 'site_configs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_configs_key'), table_name='site_configs')
    op.drop_index(op.f('ix_site_configs_id'), table_name='site_configs')
    op.drop_table('site_configs')
    # ### end Alembic commands ###
