"""添加日志系统数据库表

Revision ID: f5fcb9d73be2
Revises: 184cdcc9ff90
Create Date: 2025-08-02 11:38:29.735518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5fcb9d73be2'
down_revision: Union[str, Sequence[str], None] = '184cdcc9ff90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_method_timestamp', 'access_logs', ['method', 'timestamp'], unique=False)
    op.create_index('idx_access_path_timestamp', 'access_logs', ['path', 'timestamp'], unique=False)
    op.create_index('idx_access_status_timestamp', 'access_logs', ['status_code', 'timestamp'], unique=False)
    op.create_index('idx_access_user_timestamp', 'access_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_ip_address'), 'access_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_access_logs_log_id'), 'access_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_access_logs_method'), 'access_logs', ['method'], unique=False)
    op.create_index(op.f('ix_access_logs_path'), 'access_logs', ['path'], unique=False)
    op.create_index(op.f('ix_access_logs_request_id'), 'access_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_access_logs_status_code'), 'access_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_access_logs_timestamp'), 'access_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_event_timestamp', 'security_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_security_ip_timestamp', 'security_logs', ['ip_address', 'timestamp'], unique=False)
    op.create_index('idx_security_severity_timestamp', 'security_logs', ['severity', 'timestamp'], unique=False)
    op.create_index('idx_security_user_timestamp', 'security_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_event_type'), 'security_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_logs_ip_address'), 'security_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_logs_log_id'), 'security_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_security_logs_severity'), 'security_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_logs_timestamp'), 'security_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_user_id'), 'security_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_logs_username'), 'security_logs', ['username'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('log_type', sa.String(length=20), nullable=False),
    sa.Column('logger_name', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('exception_type', sa.String(length=100), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_ip_timestamp', 'system_logs', ['ip_address', 'timestamp'], unique=False)
    op.create_index('idx_logs_timestamp_level', 'system_logs', ['timestamp', 'level'], unique=False)
    op.create_index('idx_logs_type_timestamp', 'system_logs', ['log_type', 'timestamp'], unique=False)
    op.create_index('idx_logs_user_timestamp', 'system_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_correlation_id'), 'system_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_log_id'), 'system_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_system_logs_log_type'), 'system_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_log_type'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_log_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_correlation_id'), table_name='system_logs')
    op.drop_index('idx_logs_user_timestamp', table_name='system_logs')
    op.drop_index('idx_logs_type_timestamp', table_name='system_logs')
    op.drop_index('idx_logs_timestamp_level', table_name='system_logs')
    op.drop_index('idx_logs_ip_timestamp', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_security_logs_username'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_user_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_timestamp'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_severity'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_log_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_ip_address'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_event_type'), table_name='security_logs')
    op.drop_index('idx_security_user_timestamp', table_name='security_logs')
    op.drop_index('idx_security_severity_timestamp', table_name='security_logs')
    op.drop_index('idx_security_ip_timestamp', table_name='security_logs')
    op.drop_index('idx_security_event_timestamp', table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_timestamp'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_status_code'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_request_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_path'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_method'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_log_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_ip_address'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index('idx_access_user_timestamp', table_name='access_logs')
    op.drop_index('idx_access_status_timestamp', table_name='access_logs')
    op.drop_index('idx_access_path_timestamp', table_name='access_logs')
    op.drop_index('idx_access_method_timestamp', table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
